In [27]:
import pyfits as pf
import numpy as np

Opening a .fits file

In [28]:
hdulist = pf.open('/Users/Francis/fermiTools/practiceFermiTools/3C279_binned_cmap_small.fits')

In [29]:
hdulist[1]

In [30]:
hdulist.info()

Filename: /Users/Francis/fermiTools/practiceFermiTools/3C279_binned_cmap_small.fits
No.    Name         Type      Cards   Dimensions   Format
0    PRIMARY     PrimaryHDU     127   (200, 200)   int32   
1    GTI         BinTableHDU     48   12027R x 2C   [D, D]   


In [31]:
hdulist[0].header[27]

'TT'

In [38]:
scidata = hdulist['GTI'].data

In [39]:
print scidata

[(239557417.49417615, 239558069.09306949)
 (239559567.98007262, 239563954.08429933)
 (239565647.9856663, 239569844.08451673) ...,
 (302564765.63283199, 302567515.085356)
 (302567528.63027132, 302570220.08546305) (302571570.63295758, 302572802.0)]


In [42]:
scidata.shape

(12027,)

In [47]:
scidata[0][1]

239558069.09306949

In [48]:
data = hdulist[0].data

In [49]:
print data

[[16 23 21 ..., 13 14  6]
 [17 21 13 ..., 11 18 10]
 [11 18 19 ..., 14 10 17]
 ..., 
 [12  9 11 ...,  7 12 15]
 [18 16 15 ..., 15 11 12]
 [17 16 19 ..., 11 13 13]]


In [50]:
print data[0]

[16 23 21 19 18 21 13 20 15 15 24 17 10 17 17 15 18 25 23 13 18 14  9 16 15
 17 21 16 18 14 10 20 20 13 18 16 18 19 30 22 11 24 22 18 22 18 19 21 21 29
 15 23 19 14 16 16 13 18 16 12 23 20 17 20 24 10 16 23 21 18 21 16 19 18 20
 21 18 22 14 16 18 17 23 12 21 18 19 21 22 26 18 16 17 13 25 27 15 22 17 27
 19 23 30 17 26 33 38 42 46 54 76 60 54 39 29 40 23 24 29 22 23 23 25 20 18
 16 26 24 20 24 21 24 18 16 20 17 28 21 16 16 22 14 21 17 18 17 24 20 19 16
 31 18 16 21 28 21 21 34 22 26 22 18 14 23 14 14 13 24 20 18 14 16 17 14 19
 15 13 14 23 18 12 14 11 17 18 14 17  8 16 12 22 10 20 19 15 15 10 13 14  6]


In [51]:
print data[0,0]

16


In [52]:
print data[0,-2]

14


In [53]:
print data[0,:11]

[16 23 21 19 18 21 13 20 15 15 24]


In [54]:
print data[:2,:11]

[[16 23 21 19 18 21 13 20 15 15 24]
 [17 21 13 22 23 20 18 20 12 13 29]]
